# Generated by Django 4.0.3 on 2022-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120, unique=True)),
                ('mobile_brand', models.CharField(max_length=80)),
                ('price', models.PositiveIntegerField()),
                ('number_of_pieces', models.PositiveIntegerField()),
            ],
        ),
    ]
