# Generated by Django 4.0.3 on 2022-03-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
